{"links": {"self": {"href": "data/repositories/osrf/subt/issues/224/comments/54616693.json"}, "html": {"href": "#!/osrf/subt/issues/224#comment-54616693"}}, "issue": {"links": {"self": {"href": "data/repositories/osrf/subt/issues/224.json"}}, "type": "issue", "id": 224, "repository": {"links": {"self": {"href": "data/repositories/osrf/subt.json"}, "html": {"href": "#!/osrf/subt"}, "avatar": {"href": "data/bytebucket.org/ravatar/{3c95f6ad-c304-407c-b838-09597d836552}ts=2272898"}}, "type": "repository", "name": "subt", "full_name": "osrf/subt", "uuid": "{3c95f6ad-c304-407c-b838-09597d836552}"}, "title": "/subt/pose_from_artifact_origin after return from tunnel?"}, "content": {"raw": "OK, thanks for info. Nate wrote \u201cWe check the distance from the robot\u201d so is it possible that if you are at some corner it would fail?\n\n\u200c\n\n```\n135.588000000 INFO /subt_solution [/home/developer/subt_solution/src/subt_seed/src/subt_seed_node.cc:403(getSpeedCmd)] [topics: ] Python3: stdout Waiting for origin ... \r\n135.640000000 INFO /subt_solution [/home/developer/subt_solution/src/subt_seed/src/subt_seed_node.cc:403(getSpeedCmd)] [topics: ] Python3: stdout Origin: [-5.0, -8.0, 0.075941] C10F100F400F1000L \r\n\r\n325.072000000 INFO /subt_solution [/home/developer/subt_solution/src/subt_seed/src/subt_seed_node.cc:403(getSpeedCmd)] [topics: ] Python3: stdout Final xyz: (-3.246876248876756, 2.3147173289336958, 0.16469927643030938) \r\n325.072000000 INFO /subt_solution [/home/developer/subt_solution/src/subt_seed/src/subt_seed_node.cc:403(getSpeedCmd)] [topics: ] Python3: stdout Final xyz (DARPA coord system): (-8.246876248876756, -5.685282671066304, 0.24064027643030939) \r\n\r\n325.072000000 INFO /subt_solution [/home/developer/subt_solution/src/subt_seed/src/subt_seed_node.cc:403(getSpeedCmd)] [topics: ] Python3: stdout Waiting for origin ...\r\n328.476000000 ERROR /subt_solution [/home/developer/subt_solution/src/subt_seed/src/subt_seed_node.cc:284(Update)] [topics: ] Failed to call pose_from_artifact_origin service, robot may not exist, be outside staging area, or the service is not available. \r\n328.476000000 INFO /subt_solution [/home/developer/subt_solution/src/subt_seed/src/subt_seed_node.cc:403(getSpeedCmd)] [topics: ] Python3: stdout Origin ERROR received\r\n328.476000000 INFO /subt_solution [/home/developer/subt_solution/src/subt_seed/src/subt_seed_node.cc:403(getSpeedCmd)] [topics: ] Python3: stdout Origin: None C10F100F400F1000L\r\n328.476000000 INFO /subt_solution [/home/developer/subt_solution/src/subt_seed/src/subt_seed_node.cc:403(getSpeedCmd)] [topics: ] Python3: stdout Lost in tunnel: True (-5.0, -8.0, 0.075941) \r\n\r\n```\n\nso can you go to particular coordinates?", "markup": "markdown", "html": "<p>OK, thanks for info. Nate wrote \u201cWe check the distance from the robot\u201d so is it possible that if you are at some corner it would fail?</p>\n<p>\u200c</p>\n<div class=\"codehilite\"><pre><span></span>135.588000000 INFO /subt_solution [/home/developer/subt_solution/src/subt_seed/src/subt_seed_node.cc:403(getSpeedCmd)] [topics: ] Python3: stdout Waiting for origin ... \n135.640000000 INFO /subt_solution [/home/developer/subt_solution/src/subt_seed/src/subt_seed_node.cc:403(getSpeedCmd)] [topics: ] Python3: stdout Origin: [-5.0, -8.0, 0.075941] C10F100F400F1000L \n\n325.072000000 INFO /subt_solution [/home/developer/subt_solution/src/subt_seed/src/subt_seed_node.cc:403(getSpeedCmd)] [topics: ] Python3: stdout Final xyz: (-3.246876248876756, 2.3147173289336958, 0.16469927643030938) \n325.072000000 INFO /subt_solution [/home/developer/subt_solution/src/subt_seed/src/subt_seed_node.cc:403(getSpeedCmd)] [topics: ] Python3: stdout Final xyz (DARPA coord system): (-8.246876248876756, -5.685282671066304, 0.24064027643030939) \n\n325.072000000 INFO /subt_solution [/home/developer/subt_solution/src/subt_seed/src/subt_seed_node.cc:403(getSpeedCmd)] [topics: ] Python3: stdout Waiting for origin ...\n328.476000000 ERROR /subt_solution [/home/developer/subt_solution/src/subt_seed/src/subt_seed_node.cc:284(Update)] [topics: ] Failed to call pose_from_artifact_origin service, robot may not exist, be outside staging area, or the service is not available. \n328.476000000 INFO /subt_solution [/home/developer/subt_solution/src/subt_seed/src/subt_seed_node.cc:403(getSpeedCmd)] [topics: ] Python3: stdout Origin ERROR received\n328.476000000 INFO /subt_solution [/home/developer/subt_solution/src/subt_seed/src/subt_seed_node.cc:403(getSpeedCmd)] [topics: ] Python3: stdout Origin: None C10F100F400F1000L\n328.476000000 INFO /subt_solution [/home/developer/subt_solution/src/subt_seed/src/subt_seed_node.cc:403(getSpeedCmd)] [topics: ] Python3: stdout Lost in tunnel: True (-5.0, -8.0, 0.075941) \n</pre></div>\n\n\n<p>so can you go to particular coordinates?</p>", "type": "rendered"}, "created_on": "2019-10-31T14:01:31.927874+00:00", "user": {"display_name": "Martin Dlouhy", "uuid": "{27de76db-249c-44be-9eb8-91a3b17bf0d7}", "links": {"self": {"href": "https://api.bitbucket.org/2.0/users/%7B27de76db-249c-44be-9eb8-91a3b17bf0d7%7D"}, "html": {"href": "https://bitbucket.org/%7B27de76db-249c-44be-9eb8-91a3b17bf0d7%7D/"}, "avatar": {"href": "data/secure.gravatar.com/avatar/85a9b1d43839b393296feb3b35a2e577d=httpsavatar-management--avatars.us-west-2.prod.public.atl-paas.netinitialsMD-1.png"}}, "nickname": "robotikacz", "type": "user", "account_id": "557058:490c665b-b69c-40f3-80ea-64f20747efc4"}, "updated_on": null, "type": "issue_comment", "id": 54616693}