{"changes": {"content": {"new": "This is probably just something I\u2019m doing wrong, so my apologies for bothering everyone else with this, but I wanted to ask if anyone else has had move\\_base sporadically fail with the error: \r\n\r\n```\r\nUnable to get starting pose of robot, unable to create global plan\r\n```\r\n\r\nI\u2019m seeing this sporadically but very frequently in a lot of CloudSim logs. Never saw it happen locally. I was assuming it might be related to one of the CloudSim issues before the urban competition, but now I\u2019m not so sure. When it happens, it fills up the logs with the same message over and over, and the robot never recovers. I\u2019m guessing it might be \\(directly or indirectly\\) caused by some sort of a SLAM failure, but it just seems a little strange I\u2019ve never had it happen in local testing.\r\n\r\nAnyway, I will keep on digging \\(pun intended\\) into this a lot more here, but just wanted to quickly ask if anyone else has seen something like this?\r\n\r\nThanks, much appreciated!", "old": "This is probably just something I\u2019m doing wrong, so my apologies for bothering everyone else with this, but I wanted to ask if anyone else has had move\\_base sporadically fail with the error: \\`Unable to get starting pose of robot, unable to create global plan\\`. I\u2019m seeing this sporadically but very frequently in a lot of CloudSim logs. Never saw it happen locally. I was assuming it might be related to one of the CloudSim issues before the urban competition, but now I\u2019m not so sure. When it happens, it fills up the logs with the same message over and over, and the robot never recovers. I\u2019m guessing it might be \\(directly or indirectly\\) caused by some sort of a SLAM failure, but it just seems a little strange I\u2019ve never had it happen in local testing.\r\n\r\nAnyway, I will keep on digging \\(pun intended\\) into this a lot more here, but just wanted to quickly ask if anyone else has seen something like this?\r\n\r\nThanks, much appreciated!"}}, "links": {"self": {"href": "data/repositories/osrf/subt/issues/348/changes/56360506.json"}, "html": {"href": "#!/osrf/subt/issues/348#comment-56360506"}}, "issue": {"links": {"self": {"href": "data/repositories/osrf/subt/issues/348.json"}}, "type": "issue", "id": 348, "repository": {"links": {"self": {"href": "data/repositories/osrf/subt.json"}, "html": {"href": "#!/osrf/subt"}, "avatar": {"href": "data/bytebucket.org/ravatar/{3c95f6ad-c304-407c-b838-09597d836552}ts=2272898"}}, "type": "repository", "name": "subt", "full_name": "osrf/subt", "uuid": "{3c95f6ad-c304-407c-b838-09597d836552}"}, "title": "Sporadic move_base failure in CloudSim: \"Unable to get starting pose of robot, unable to create global plan\""}, "created_on": "2020-02-29T09:17:45.645280+00:00", "user": {"display_name": "Malcolm Stagg", "uuid": "{eee13832-fdd5-4196-aa05-6cfdb1118c65}", "links": {"self": {"href": "https://api.bitbucket.org/2.0/users/%7Beee13832-fdd5-4196-aa05-6cfdb1118c65%7D"}, "html": {"href": "https://bitbucket.org/%7Beee13832-fdd5-4196-aa05-6cfdb1118c65%7D/"}, "avatar": {"href": "data/secure.gravatar.com/avatar/8c08ab97dc600bddad36e4a58f8cc5afd=httpsavatar-management--avatars.us-west-2.prod.public.atl-paas.netinitialsMS-3.png"}}, "nickname": "malcolmst7", "type": "user", "account_id": "557058:08ef8b07-1500-4917-989c-89f91ce4beac"}, "message": {"raw": null, "markup": "markdown", "html": "", "type": "rendered"}, "type": "issue_change", "id": 56360506}