{"priority": "major", "kind": "bug", "repository": {"links": {"self": {"href": "data/repositories/osrf/subt.json"}, "html": {"href": "#!/osrf/subt"}, "avatar": {"href": "data/bytebucket.org/ravatar/{3c95f6ad-c304-407c-b838-09597d836552}ts=2272898"}}, "type": "repository", "name": "subt", "full_name": "osrf/subt", "uuid": "{3c95f6ad-c304-407c-b838-09597d836552}"}, "links": {"attachments": {"href": "data/repositories/osrf/subt/issues/275/attachments_page=1.json"}, "self": {"href": "data/repositories/osrf/subt/issues/275.json"}, "watch": {"href": "https://api.bitbucket.org/2.0/repositories/osrf/subt/issues/275/watch"}, "comments": {"href": "data/repositories/osrf/subt/issues/275/comments_page=1.json"}, "html": {"href": "#!/osrf/subt/issues/275/help-needed-with-generating-of-a-new-model"}, "vote": {"href": "https://api.bitbucket.org/2.0/repositories/osrf/subt/issues/275/vote"}}, "reporter": {"display_name": "Sophisticated Engineering", "uuid": "{12ed2357-e253-4c67-a2b9-7e12c64773e4}", "links": {"self": {"href": "https://api.bitbucket.org/2.0/users/%7B12ed2357-e253-4c67-a2b9-7e12c64773e4%7D"}, "html": {"href": "https://bitbucket.org/%7B12ed2357-e253-4c67-a2b9-7e12c64773e4%7D/"}, "avatar": {"href": "data/secure.gravatar.com/avatar/2a19963da6b0f34b3be28d8690bdd711d=httpsavatar-management--avatars.us-west-2.prod.public.atl-paas.netinitialsSE-6.png"}}, "nickname": "sopheng", "type": "user", "account_id": "5c0d82b3128c7106f57691a7"}, "title": "Help needed with generating of a new Model Configuration", "component": null, "votes": 0, "watches": 1, "content": {"raw": "I followed the description for the [Model Submission Process](#!/osrf/subt/wiki/Model%20Submission%20Process) . I downloaded the X2 model from fuel an copied it into the submitted\\_models folder. When I tied to launch the model locally I first got errors that the link in `<uri>model://X2/meshes/x2_chassis.dae</uri>` could not be resolved. So I changed to `<uri>meshes/x2_chassis.dae</uri> ` \r\n\r\nNow I get the error `[GUI] [Err] [Material.cc:143] Unable to find texture[../materials/textures/x2.png] in path \u2026`\r\n\r\nWhat am I doing wrong? I did not expect such errors :-\\(", "markup": "markdown", "html": "<p>I followed the description for the <a data-is-external-link=\"true\" href=\"#!/osrf/subt/wiki/Model%20Submission%20Process\" rel=\"nofollow\">Model Submission Process</a> . I downloaded the X2 model from fuel an copied it into the submitted_models folder. When I tied to launch the model locally I first got errors that the link in <code>&lt;uri&gt;model://X2/meshes/x2_chassis.dae&lt;/uri&gt;</code> could not be resolved. So I changed to <code>&lt;uri&gt;meshes/x2_chassis.dae&lt;/uri&gt;</code> </p>\n<p>Now I get the error <code>[GUI] [Err] [Material.cc:143] Unable to find texture[../materials/textures/x2.png] in path \u2026</code></p>\n<p>What am I doing wrong? I did not expect such errors :-(</p>", "type": "rendered"}, "assignee": {"display_name": "Arthur Schang", "uuid": "{1403972a-9b64-442b-a69c-d7e9557e1d87}", "links": {"self": {"href": "https://api.bitbucket.org/2.0/users/%7B1403972a-9b64-442b-a69c-d7e9557e1d87%7D"}, "html": {"href": "https://bitbucket.org/%7B1403972a-9b64-442b-a69c-d7e9557e1d87%7D/"}, "avatar": {"href": "https://avatar-management--avatars.us-west-2.prod.public.atl-paas.net/initials/AS-0.png"}}, "nickname": "Arthur Schang", "type": "user", "account_id": "557058:14b7fd50-d65a-47a8-825c-fa89681d07bd"}, "state": "resolved", "version": null, "edited_on": null, "created_on": "2019-11-28T21:07:22.556900+00:00", "milestone": null, "updated_on": "2019-11-28T22:38:33.144874+00:00", "type": "issue", "id": 275}